pgvector:
  host: localhost
  port: 5432
  dbname: postgres
  user: postgres
  password: your_password

milvus:
  host: localhost
  port: 19530

qdrant:
  host: localhost
  port: 6333
  grpc_port: 6334

weaviate:
  host: http://localhost:8080
  grpc_port: 50051